### DISCUSSION TITLE
Targets or subscription groups?

### DISCUSSION THREAD

**Discussion by hellt** [karimra/gnmic#256] [Ideas]
A potential bottle neck that gnmic config has is the necessity to bind subscriptions and outputs per each target.

Consider having 100 targets and 5 subscriptions, it becomes very cumbersome to maintain the list of bindings between targets, subs and outputs.

Maybe to think about target groups, which will aggregate target addresses?

**Comment by karimra** [comment]
Can you show an example of how that config might look like ?

**Reply by hellt** [reply]
didn't give it too much thought, but maybe smth like that

```yaml
targets:
  all: # group name
    members:
      - leaf1:
      - leaf2:
          subscriptions:
            - cpu # per-target subscription
      - spine1:
    subscriptions:
      - interface_stats # subscriptions to apply to all members
    outputs:
      - prom # outputs to apply to all members of the group

  leafs: # group name
    members:
      - leaf1:
      - leaf2:
    subscriptions:
      - bgp_stats
```
