### DISCUSSION TITLE
Main configuration file change reflect without restart the application

### DISCUSSION THREAD

**Discussion by dshah2012** [karimra/gnmic#403] [Q&A]
Hello,

I have a question, do we have any way  in gnmic application that can constantly check for the main configuration file  if a new configuration file is loaded without restarting the application.

Regards,
Darshan

**Comment by karimra** [comment]
Hi,

Not exactly, but there is an option to specify a target file that gnmic will watch for added and removed targets:
https://gnmic.kmrd.dev/user_guide/target_loaders/#file-target-loader

**Comment by dshah2012** [comment]
Thanks @karimra, yes i saw that yesterday. Just wanted to know if we had for main configuration file too.

**Reply by karimra** [reply]
What is your use case for rereading all the config that is not fulfilled by a full restart ?

**Reply by dshah2012** [reply]
@karimra  Since we have many devices in place, that has different active interfaces, so when we define the subscriptions in the main configuration file we defined at the beginning for that target devices.  In later stage when we add new targets(device IP) in the target loader file that might have different active interfaces which needs to be subscribed. 

Just a quick follow up question, by adding the new target in the target-file-loader,  how the application decides which subscription the new target will use, sorry for asking some trivial question just wanted to know how this works ?

**Reply by karimra** [reply]
You can define the subscriptions with wild card keys for the interface name, and filter out the interfaces you don't need in gnmic or at your post processing system.

When a new target is added, gnmic follows the same logic as during a first startup:
The subscriptions applied to the target are the ones under its `subscriptions` field (a strings list).
If the target is not explicitly associated with any subscription, all of the defined subscriptions defined in the config file main are implicitly associated to it.

**Reply by dshah2012** [reply]
Thanks for the response. Sure I can do that.

**Reply by dshah2012** [reply]
@karimra 
I was trying to add a new target like below in the target-config.yaml file for dynamic target update.

router ip address:
    username: username
    password: password
    insecure: true
    subscription:
      -  existing subsription_name in main configuration
     outputs:
      -  existing output in main configuration

and added this in main configuration file.

loader:
  type: file
  file: targets-config.yaml
  interval: 5s
  
 Is this right?

**Reply by karimra** [reply]
The file should have the routers names or IPs as a keys:
See this page: https://gnmic.kmrd.dev/user_guide/target_discovery/file_discovery/

Each target can contain the keys shown here: https://gnmic.kmrd.dev/user_guide/targets/#target-configuration-options


Except the yaml indentation, I can see that you are missing a key for the target parameters as well as `subscriptions` not `subscription`

**Reply by dshah2012** [reply]
Oh okay. Thanks. So it will be something like this or am i missing any key again. I did according to the target configuration parameters page.

```
router_ip_address:
    username: username
    password: password
    insecure: true
    address: routers_ip_address
subscriptions:
   - existing subsription_name in main configuration
outputs:
   - existing output in main configuration
```

**Reply by karimra** [reply]
`subscriptions` and `outputs` keys should be under the `router_ip_address` key.
```yaml
router_ip_address:
  username: username
  password: password
  insecure: true
  address: routers_ip_address
  subscriptions:
    - existing subsription_name in main configuration
  outputs:
    - existing output in main configuration
```

If you omit `subscriptions` and `outputs`, all the ones (subscriptions and outputs) defined in the main config file will apply.
