### DISCUSSION TITLE
Multiple encoding in single main configuration not supported

### DISCUSSION THREAD

**Discussion by dshah2012** [karimra/gnmic#420] [Q&A]
Hi @karimra ,

I was looking at the encoding part. Is it possible to give different encoding in a single main configuration file. 

Regards,
Darshan

**Comment by karimra** [comment]
> Hi @karimra ,
> 
> I was looking at the encoding part. Is it possible to give different encoding in a single main configuration file. 
> 
> Regards,
> Darshan

Yes, you can set the encoding per subscription.

**Reply by dshah2012** [reply]
Okay thanks. One more thing.
Suppose i have a target defined in main configuration with a certificate.` tls-ca` is defined in the global variable pointing to the global variable.

```
nokia:
    name: nokia
    address: ip_address:57400
    username: username
    password: password
    skip-verify: true
    subscriptions:
      - subscription_1
    outputs:
      - output_1
```

It works fine.

Now when i tried to removed the entry under the target from the main configuration file and added to the target loader file. I mentioned the loader details in the main configuration file the location and other things.
In this scenario it throws an error saying. It loads the target file correctly but it throws this error for the the same target that was working when it was in main configuration file. 

`transport: authentication handshake failed: x509: cannot validate certificate for router_ip_address  because it doesn't contain any IP SANs`

Is there anything i am missing?

**Reply by karimra** [reply]
do you see the `tls-ca` file name in the target config ?
can you show the targets file ?

**Reply by dshah2012** [reply]
Yes it there but its weird that it does not contain skip-verify as true as that was declared in the target file. In the log i see the config has `"skip-verify":false`
This is the config from the log
`{"name":"CR02-Nokia","address":"ip_address:57400","username":"username","password":"password","timeout":10000000000,"insecure":false,"tls-ca":"/data/ceritficate.pem","tls-cert":"","tls-key":"","skip-verify":false,"subscriptions":["subscriptions"],"outputs":["ouputs"],"buffer-size":1000,"retry-timer":10000000000,"gzip":false,"token":""}`

Target file config.
```
nokia:
    name: nokia
    address: ip_address:57400
    username: username
    password: password
    skip-verify: true
    subscriptions:
      - subscriptions
    outputs:
      - outputs
```
