### DISCUSSION TITLE
Cluster deployment using kubernetes

### DISCUSSION THREAD

**Discussion by dshah2012** [karimra/gnmic#437] [Q&A]
Hello @karimra ,

I am trying the cluster feature of the gnmic and have this doubt. I am building a helm chart that will deploy the gnmic to the kubernetes environmet in a cluster mode. I was looking at the examples of docker-compose.yaml for a reference. I see in the  documentation that the at the start-up phase that the gnmic-api address are registered which would be different if we provide that for different gnmic instance. But the thing in deployment is that we specify the replicas and it will handle the replication for that pods/containers. In this case the GNMIC_API and GNMIC_CLUSTERING_INSTANCE_NAME and GNMIC_CLUSTERING_SERVICE_ADDRESS would remain same and just one instance would be registered. So does it mean that the leader will be just one as there are no other distinctive instances and are the targets been distributed in instance based upon the load irrespective of the GNMIC_CLUSTERING_INSTANCE_NAM, GNMIC_CLUSTERING_SERVICE_ADDRES ?

**Comment by karimra** [comment]
Hi @dshah2012 ,

The API port number does not have to be different, as long as the pods get different IPs.

The instance name and service address cannot be the same, there will be no clustering in this case.

I would run each gNMIc instance together with a consul instance in the same pod, in this case there is no need to specify an IP for gNMIc's API, a port number is enough, the Consul agent will add its own IP (which would also be gNMIc's) as the service IP.
In this case you also dont need to care about the `service address`.
Check Consul architecture if you haven't. You can run it in server mode or in client mode, you only need 1, 3 or 5 servers, all the others can be clients. Consul clients are light weight, so you can run them in all you pods.

As for the `instance-name`, you can use k8s `initContainers` to edit the config file before `gNMIc` container boots.

**Reply by dshah2012** [reply]
Thanks @karimra .
Ya sure i will try the approach that you have mentioned. With once GNMIC and consul in one pod  and do  replication factor of more than 1.  GNMIC_API port number will remain same for all the pods as they would be under same deployment and the IP's will be different as there are different pods.  
So i have to run the consul server as a separate deployment and also run consul clients with gnmic in one pod ?
For the instance name since its a single deployment, even tough i have the initContainer it will give the same name for all the pods if we edit in the config since we will be doing it for once.

**Reply by karimra** [reply]
yes, run the consul server separately ( maybe a statefulSet ?)

your pod will be `gnmic` + `consul client` + `initContainer`, the script in the init container should take into consideration the pod name that you can expose via env vars. You can just set the instance name to the pod name, it does not have to be fancy

**Reply by dshah2012** [reply]
Sure Thanks for the advice.
Will try the approach and let you know.

**Reply by dshah2012** [reply]
Hello @karimra 
I have deployed the consul server cluster with 3 instances for now with use of their official helm charts. 
Next :
Created deployment config for gnmic + consul client. Could you please let me know the gnmic container configuration part is correct 
I Used the GNMIC_API as just ':7890' 
For the GNMIC_CLUSTERING_INSTANCE_NAME - used the Nodename
and for the GNMIC_CLUSTERING_SERVICE_ADDRESS - its pod IP.

Deployment file: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gnmic-collector-with-consul"
  namespace: "test"
  labels:
    app: "gnmic-collector-with-consul"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "gnmic-collector-with-consul"
  template:
    metadata:
      labels:
        app: "gnmic-collector-with-consul"
    spec:
      containers:
        - name: consul-agent
          image: hashicorp/consul:1.10.0
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8502
              name: grpc
            - containerPort: 8301
              protocol: "TCP"
              name: serflan-tcp
            - containerPort: 8301
              protocol: "UDP"
              name: serflan-udp
            - containerPort: 8600
              name: dns-tcp
              protocol: "TCP"
            - containerPort: 8600
              name: dns-udp
              protocol: "UDP"
          volumeMounts:
            - name: pipeline-conf-volume
              mountPath: /consul/data
            - name: config
              mountPath: /consul/config
          env:
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-ec"
                - |
                  curl http://127.0.0.1:8500/v1/status/leader \
                  2>/dev/null | grep -E '".+"'
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              memory: '100Mi'
              cpu: '100m'
            limits:
              memory: '100Mi'
              cpu: '100m'
          command: 
            - "/bin/sh"
            - "-ec"
            - |
              CONSUL_FULLNAME="consul"
              exec /bin/consul agent \
                -node="${NODE}" \
                -advertise="${ADVERTISE_IP}" \
                -config-dir=/consul/config \
                -datacenter={{ .Values.consul.dataCenter }} \
                -data-dir=/consul/data \
                -retry-join="${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
                -retry-join="${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
                -retry-join="${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc:8301" \
                -domain=consul
        - name: gnmicCollector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: always
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7890
          command: ["/app/gnmic"]
          args: ["subscribe", "--config=/etc/pipeline/cfg/gnmic.yaml"]
          env:
            - name: GNMIC_API
              value: ':7890'
            - name: GNMIC_CLUSTERING_INSTANCE_NAME
              value: '${NODE}'
            - name: GNMIC_CLUSTERING_SERVICE_ADDRESS
              value: '${POD_IP}'
            - name: GNMIC_LOG_FILE
              value: "/etc/pipeline/log/pipeline.log"
          volumeMounts:
            - name: "pipeline-conf-volume"
              mountPath: /etc/pipeline/cfg/
              subPath: "gnmic.yaml"
            - name: "pipeline-conf-volume"
              mountPath: /etc/pipeline/target/
              subPath: "target_file.yaml"
            - name: "pipeline-conf-volume"
              mountPath: /etc/pipeline/log/
              subPath: "pipeline.log"
      volumes:
        - name: config
          configMap:
            name: consul-config
        - name: pipeline-conf-volume
          emptyDir: {}

```

```
consul-dns      ClusterIP   10.102.6.92     <none>        53/TCP,53/UDP                                                             19s
consul-server   ClusterIP   None            <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   19s
consul-ui       NodePort    10.101.148.64   <none>        80:31457/TCP                                                              19s
```
In the gnmic file. The address should be of the main consul server name right that is the second one from the above output or it should be one of the service of the three consul server ?
I have added the consul-server:8500 as the address in the clustering address as below.

```
clustering:
  cluster-name: cluster1
  targets-watch-timer: 30s
  locker:
    type: consul
    address: consul-server:8500
```

I was getting this error in gnmic instance container having the gnmic service address environment variable and when i removed that environment variable the issue persist :
`[gnmic] 2021/08/12 03:06:48.999423 /build/app/clustering.go:299: failed assigning target "device-name" to service "gnmic-7f53e72d-d052-439b-bc24-538ec210d54c-api": Post http://10.42.109.198:7890/config/targets: dial tcp 10.42.109.198:7890: connect: connection refused`

I was also not sure which service is gnmic trying to connect because I dont have any service with name `gnmic-7f53e72d-d052-439b-bc24-538ec210d54c-api` .

**Reply by karimra** [reply]
That service name is the gnmic API service instance registered in consul.
If the `instance-name` is not set under `clustering`, and random instance name will be generated in the format `gnmic-$UUID`

It looks like you defined the `env` key twice under `gnmic` container spec which results in an empty `$NODE` variable.
set the `env` section this way:
 ```yaml
env:
  - name: GNMIC_API
    value: ":7890"
  - name: GNMIC_LOG_FILE
    value: "/etc/pipeline/log/pipeline.log"
  - name: GNMIC_CLUSTERING_INSTANCE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: GNMIC_CLUSTERING_SERVICE_ADDRESS
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
```

About consul, gnmic should reach out to the consul agent located in the same pod.
You need to make sure that the consul agent is connected to the consul main server.

**Reply by dshah2012** [reply]
ah did not see that thanks i thought i had just one env section defined.

I can see the consul client is connected to the consul cluster. I was checking that using the consul members from inside one of the consul server, which shows the all the members connected to the cluster.

consul-server-0              10.42.85.126:8301   alive   server  1.9.2   2         dc1  <all>
consul-server-1              10.42.128.52:8301   alive   server  1.9.2   2         dc1  <all>
consul-server-2              10.42.109.198:8301  alive   server  1.9.2   2         dc1  <all>
nodename(consul client name for example: test.ca)      10.42.94.90:8301    alive   client  1.10.0  2         dc1  <default>


So in the main configuration file i just need to mention the localhost:8500 which will contact the consul agent that is running as client in the same pod. Will these work?
```
clustering:
  cluster-name: cluster1
  targets-watch-timer: 30s
  locker:
    type: consul
    address: localhost:8500
```
