### DISCUSSION TITLE
GET RPC call path using the configuration file

### DISCUSSION THREAD

**Discussion by dshah2012** [karimra/gnmic#478] [Q&A]
Hello @karimra ,

I have a question regarding the get and set configuration.  Does get and set path is also supported using the file based configuration. If yes, Is there any example configuration file that is present in the repository for the GET RPC call path like we have for the subscription based.

Regards,
Darshan

**Comment by karimra** [comment]
Hi @dshah2012 

Yes both RPCs are supported using file config.
- Get RPC: 
```yaml
get-path: # equivalent to: gnmic get --path
get-type: # equivalent to : gnmic get --type
...
```

- Set RPC:
you can follow the same logic as Get RPC ( i.e : $cmd-$flag )
Or you can use the `--request-file` format explained here: https://gnmic.kmrd.dev/cmd/set/#template-based-set-request
the `request-file` can be static file or a gotemplate rendered against variables supplied using the flag `--request-vars`

Regards,
Karim

**Reply by dshah2012** [reply]
Thanks @karimra for the info. So the paths the get-path and get-type comes under any sections Like we had subscriptions sections in the file config for subscribing paths. 

1.  Can I just remove the subscriptions section and add the get-path and get-type.  Or we can add it like subscription section. 
2.  Also retrieval of data from the path like every X seconds since its a get call. Should be defined in the global ?
3.  Can be target 

Configuration file

```
insecure: true
encoding: json_ietf
log: true
get-path:
  - /configure/system/name
  - /state/system/version


targets:
  ipaddress:
    username: gnmic
    password: secret_password
   ---replace this section---
    **subscriptions:
      - sub1**
   ---------------------- 
    outputs:
      - kafka-output

//replace below section with some get-----------------------
**subscriptions:
  sub1:
    paths:
      - /interface/statistics
    stream-mode: sample
    sample-interval: 1s**
//-----------------------

outputs:
  kafka-output:
    type: kafka
    address: kafka-server:9092
    topic: telemetry
``` 

Is this correct or am I missing something, get-path will be applied to al the targets right?
