### DISCUSSION TITLE
Binding different subscriptions to multiple targets via CLI flags

### DISCUSSION THREAD

**Discussion by szebedy** [karimra/gnmic#588] [Q&A] [answered]
I have the following example configuration where different subscriptions are bound to multiple targets:

```
targets:
  device_1:  
    address: "address_1"   
    subscriptions:
      - sub_1
      - sub_2

  device_2:  
    address: "address_2"
    subscriptions:
      - sub_2
      - sub_3
	  
subscriptions:
  sub_1:
    paths:
      - "/path/1"
  sub_2:
    paths:
      - "/path/2"
  sub_3:
    paths:
      - "/path/3"
```

Is it possible to achieve this with a single CLI command?

I tried the following and it did not work, because all subscriptions were bound to all targets:

`gnmic -a address_1 subscribe --path "/path/1" --path "/path/2" -a address_2 subscribe --path "/path/2" --path "/path/3"`

**Comment by karimra** [comment, marked as answer]
Hi, 

Binding different paths to different targets on the cli is not possible, the subscribe cli command creates a single subscription that applies to all targets.

Your command created the equivalent of:
```yaml
targets:
  device_1:
    address: address_1
  device_2:
    address: address_2

subscriptions:
  sub_1:
    paths:
      - /path/1
      - /path/2
      - /path/3
```
