### DISCUSSION TITLE
kafka input

### DISCUSSION THREAD

**Discussion by jrametta** [karimra/gnmic#603] [Q&A]
Hi There!  Is it possible to have kafka input only in gnmic config such as below?  If so, what are the appropriate command line args to execute?

```
inputs:
  kafka-input:
    address: clab-fgw1-kafka-server:9002
    type: kafka
    topics: telemetry
    outputs:
      - prom-output

outputs:
  prom-output:
    type: prometheus
    listen: "gnmic:9804"
    service-registration:
      address: consul-agent:8500
```

tried with subscribe (but of course there are no subscriptions)

```
docker run --rm  -v foo.yaml:/etc/gnmic.conf  ghcr.io/karimra/gnmic:latest    sub --skip-verify
Error: no subscriptions configuration found
```

thanks!
