### ISSUE TITLE
make metric prefix configurable

### ISSUE THREAD

**Issue by hellt** [karimra/gnmic#260]
Now, `gnmic`+`$subscription_name` parts are unconditionally prepended to a resulting metric which might be not what users want.
Processors can't help, since they are processed before the prefix added.

Proposal is to expose a `prefix` configuration option for prom/influx outputs which will allow to choose how prefix should look like. For example possible values:
```yaml
metric-prefix: gnmic,$subcription-name # how it is now
metric-prefix: $string # only $string is appended
metric-prefix: gnmic # only gnmic is appended
metric-prefix: $subscription-name # only subscription-name is appended
```

_Originally posted by @hellt in https://github.com/karimra/gnmic/discussions/259_
