### ISSUE TITLE
failed to set event processor

### ISSUE THREAD

**Issue by hellt** [karimra/gnmic#261]
@karimra 
with the following config
```yaml
username: admin
password: admin
port: 57400
timeout: 10s
skip-verify: true
encoding: json_ietf

targets:
  clab-telemetry01-leaf1:
  clab-telemetry01-leaf2:
  clab-telemetry01-leaf3:
  clab-telemetry01-spine1:
  clab-telemetry01-spine2:

subscriptions:
  srl_if_stats:
    paths:
      - /interface[name=ethernet-1/*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    expiration: 60s # maximum lifetime of metrics in the local cache
    debug: false
    event-processors:
      - proc-convert-strings-to-int
      - trim-prefixes
  stdout:
    type: file
    file-type: stdout
    event-processors:
      - proc-convert-strings-to-int
      - trim-prefixes
```

gnmic reports that it set the event processors only for stdout output and not prometheus:
```
❯ gnmic --config ../container-lab/lab-examples/telemetry01/gnmic-config.yml sub  --name srl_bgp_stats --log | jq .
gnmic 2021/01/04 17:20:01.055285 using config file ../container-lab/lab-examples/telemetry01/gnmic-config.yml

gnmic 2021/01/04 17:20:01.056425 adding target {"name":"clab-telemetry01-leaf1:57400","address":"clab-telemetry01-leaf1:57400","username":"admin","password":"admin","timeout":10000000000,"insecure":false,"tls-cert":"","tls-key":"","skip-verify":true,"subscriptions":["srl_bgp_stats"],"retry-timer":10000000000}

gnmic 2021/01/04 17:20:01.056436 starting output type file

gnmic 2021/01/04 17:20:01.056469 starting output type prometheus

prometheus_output 2021/01/04 17:20:01.057100 initialized prometheus output: {"Cfg":{"Listen":":9273","Path":"/metrics","Expiration":60000000000,"Debug":false,"EventProcessors":null}}

file_output 2021/01/04 17:20:01.057317 added event processor 'proc-convert-strings-to-int' of type=event-convert to file output

file_output 2021/01/04 17:20:01.057622 added event processor 'trim-prefixes' of type=event-strings to file output

file_output 2021/01/04 17:20:01.057702 initialized file output: {"Cfg":{"FileName":"","FileType":"stdout","Format":"json","Multiline":true,"Indent":"  ","Separator":"\n","EventProcessors":["proc-convert-strings-to-int","trim-prefixes"],"ConcurrencyLimit":1000}}
```
