### ISSUE TITLE
event-processors with kafka

### ISSUE THREAD

**Issue by DefunctExodus** [karimra/gnmic#263]
I have been playing with the event processors and It appears that it doesn't seem to work correctly for the kafka output

This works as expected 
```
  stdout:
    type: file
    file-type: stdout
    format: event
    event-processors:
      - trim-name-prefix
 ```

however this just seems to not work, nothing gets trimmed
```
  kafka-cluster-telemetry:
    type: kafka
    address: "some-brokers:9093"
    topic: "some-topic"
    format: event
    event-processors:
      - trim-name-prefix
 ```

I am only running a single output at a time in this scenario
