### ISSUE TITLE
Target specific Prometheus labels 

### ISSUE THREAD

**Issue by thenodon** [karimra/gnmic#357]
Thanks for a great tool. My question if its possible to access the gnmic Prometheus metrics endpoint with a  gnmic target specified. This is the same structure as the snmp_exporter and blackbox exporter, something like:
```
localhost:9804/metrics?target=test:50051
```
The reason for this is the need to add additional labels in Promethues to a specific target like role, geopos etc.
An alternative would be if it was possible in the gnmic target configuration add target specific label/tags that in the Prometheus output is added as labels.

**Comment by karimra** [comment]
Hi,

I'm afraid that the answer to your first question is that it's not possible right now, that would require adding a custom handler for a new endpoint (`/gnmic` ?) the same way `snmp_exporter` adds `/snmp` to bind a custom handler.
But it's not a bad idea, I can look into it.

For the second question:

`gnmic` adds 2 labels to all prometheus metrics, 
- `source` which is essentially `target` (might not be a bad idea to rename this).
- `subscription_name`

Not sure if the label `source` can help fulfill your use case.

If you need per target label additions, you can use the processor [`add_tag`](https://gnmic.kmrd.dev/user_guide/event_processors/event_add_tag/) with a condition based on the target name ( meaning the tag `source`)

The below processors, if used under a prometheus output, will add 2 tags to any metric that has a label with value "target1":

e.g:
```yaml
processors:
  add_tag_target1:
    event-add-tag:
      tags:
        - "target1"   # <-- this means add the tags to any message with tag_value == target1
      add: 
        new_tag1_name: "new_tag1_value"
        new_tag2_name: "new_tag2_value"

  add_tag_target2:
    event-add-tag:
      tags:
        - "target2"   # <-- this means add the tags to any message with tag_value == target2
      add: 
        other_tag1_name: "other_tag1_value"
        other_tag2_name: "other_tag2_value"
```

So you would need a processor per target to add per target labels to a prometheus output.

Dont forget to add the processor name under the prometheus output, key `processors:`
```yaml
outputs:
  my_prom_output:
    type: prometheus:
    processors:
      - add_tag_target1
      - add_tag_target2
      #.....
```

The current regex matching does not consider both tag names and tag values at the same time, but it should work for your use case.

There is an open PR to add more precise conditions for applying processors, using `jq` statements.
Once that's merged, it will be possible to use a jq condition to add a tag, something like: `.source == "target1"` 


Hopefully this helps.

**Comment by thenodon** [comment]
Thanks for your reply and feedback. I will try your suggestions, and I agree it looks like it can work for my use case. The only thing that I did not fully understand was "The current regex matching does not consider both tag names and tag values at the same time".

**Comment by karimra** [comment]
Let's consider the below processor:
```yaml
processors:
  add_tag_target1:
    event-add-tag:
      tags:
        - "target1"   # <-- this means add the tags to any message with tag_value == target1
      add: 
        new_tag1_name: "new_tag1_value"
        new_tag2_name: "new_tag2_value"
```

This matches both:
```json
{
    "tags": {
        "source": "target1"
    },
    "values": {
        "value1": 1
    }
}
```

and 

```json
{
    "tags": {
        "SOME_OTHER_TAG_NAME": "target1"
    },
    "values": {
        "value1": 1
    }
}
```

While you would want it to match only the first message.

So using the regex matching, it's not possible to specify a condition that takes into account both tag names and tag values at the same time.
