### ISSUE TITLE
Target key does not show under  "prefix" and every new message contains update key in Protojson Format

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#389]
Hello,
 
Output data from gnmic in the protojson format, I see that there is no "target" key present under the prefix section. 
Earlier gnmi collector had this "target" key in "prefix" section in the protojson format. 

Could you let me know if there is any settings to add these "target" key.
Also the messages in the protojson contains an update key at the beginning before timestamp which was not the case for earlier gnmi Collector, Could you let me know how can that be removed or avoided.
Below is one example, i have is for gnmic

```
{
    "update": {
        "timestamp": "123234242342342",
        "prefix": {
            "origin": "Cisco",
            "elem": [
                {
                    "name": "interfaces"
                },
                {
                    "name": "interface"
                },
                {
                    "name": "interface",
                    "key": {
                        "interface-name": "bundle"
                    }
                }
            ]
        },
        "update": [
            {
                "path": {
                    "elem": [
                        {
                            "name": "interface-handle"
                        }
                    ]
                },
                "val": {
                    "stringVal": "bundle"
                }
            }
     ]
 }
}
```

This is from the earlier gnmi collector that we were using.

```
{
        "timestamp": "123234242342342",
        "prefix": {
            "origin": "Cisco",
            "elem": [
                {
                    "name": "interfaces"
                },
                {
                    "name": "interface"
                },
                {
                    "name": "interface",
                    "key": {
                        "interface-name": "bundle"
                    }
                }
            ],
         "target": "target_device_name"
        },
        "update": [
            {
                "path": {
                    "elem": [
                        {
                            "name": "interface-handle"
                        }
                    ]
                },
                "val": {
                    "stringVal": "bundle"
                }
            }
     ]
 }
```

**Comment by karimra** [comment]
Hi,

Can you share the commands used to generate these outputs ?

"...the earlier gnmi collector that we were using": Are you referring to an earlier version of gnmic? or another collector ?
If it's gnmic, can you share the version and the command used ?

From: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#2221-path-target


The target field within a path is name for the target. This field MUST only ever be present on prefix paths in the corresponding request and response messages. This field is optional for clients. When set in the prefix in a request, GetRequest, SetRequest or SubscribeRequest, the field MUST be reflected in the prefix of the corresponding GetResponse, SetResponse or SubscribeResponse by a server

**Comment by dshah2012** [comment]
Thanks for the response. Earlier we were using this thehttps://github.com/cisco-ie/pipeline-gnmi collector.
For gnmic 
We are using the configuration file.

For Example we have this kind of gnmic configuration file.  


```
username: dummy
password: dummy
other global variables

targets:
 cisco:
   name: cisco
   address: ip address of the device
   subscription: 
      - subscriptionname
  output 
      - outputname

subscriptions:
     subscriptionname:
       paths:
         - path to the interface
       stream-mode: sample
      sample-interval: 20S

outputs:
 outputname:
     type: kafka
    name: anyname
    topic: name of the topic
   format: protojson
```

So where should i include the target to be visible in the the response?

**Comment by karimra** [comment]
Thanks for the details:
You can try adding a target field under `subscriptions`

```yaml
subscriptions:
     subscriptionname:
       paths:
         - path to the interface
       stream-mode: sample
       sample-interval: 20S
       target: "target_device_name"
```
