### ISSUE TITLE
Issue: Every interval different interface telemetry is being retrieved from the Device

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#393]
Hello @karimra ,

We are facing an issue in our team, we have a configuration file like this.

```
username: dummy
password: dummy
other global variables

targets:
 cisco:
   name: cisco
   address: ip address of the device
   subscription: 
      - subscriptionname
  output 
      - outputname

subscriptions:
     subscriptionname:
      target: "some_dummy_name"
       paths:
         - path to the interface like (Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-xr/interface)
       stream-mode: sample
      sample-interval: 200s

outputs:
 outputname:
     type: kafka
    name: anyname
    topic: name of the topic
   format: protojson
```

The problem is that after every 200s different interface information is being retrieved not the same interface.
For example:
During first time it would retrieve from interface like 1/6/6/45 (dummy name) and others. But after 200s it is retrieving other interface telemetry data which is not same as the previous one like completely different 1/6/6/23.

Could you let me know if there any keyword that needs to be defined.
Also i see an issue that it does not retrieve information in specified interval.
