### ISSUE TITLE
Maximum amount of subscription defined for the collector

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#397]
Hello @karimra 

I have few questions regarding the subscription. I did not find any documentation for this on the website so wanted to ask here.
1. What is the maximum amount of subscription that i can mention in each target under subscriptions ?
```
dummy_name:
    name: dummy_name
    address: router_ip_address
    subscriptions:
      - uptime
    outputs:
      - kafka

```
2. How many maximum individual subscription can be defined under subscriptions block.  ?
```
subscriptions:
  # Add subscriptions configuration here
  uptime:
    paths:
      - Cisco-IOS-XR-shellutil-oper:system-time/uptime
    stream-mode: sample
    sample-interval: 10s
    target: "dummy_target"
```
3. Ideally how paths should be defined in a subscription to handle for like interfaces, for a good performance. Is there any maximum amount here.?

Regards,
Darshan
