### ISSUE TITLE
Kafka: Support SASL_SSL 

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#411]
Hello @karimra ,

Does current gnmic support kafka output with SASL_SSL with username and password along with kafka certificates to connect to the kafka cluster.
I saw one issue that was raised earlier with the SASL username and password enhancement. Does it also support integration of the certificates too ?

**Comment by karimra** [comment]
Hi @dshah2012

TLS based connections are not supported currently, let me see if I can add it over the next few days.

**Comment by dshah2012** [comment]
Thanks .

**Comment by karimra** [comment]
@dshah2012 can you give it a try with v0.17.0 ?
configuration examples are given here: https://gnmic.kmrd.dev/user_guide/outputs/kafka_output/#security-configuration-examples

For `SASL_SSL`:

- Without server certificate verification
    ```yaml
    outputs:
      output1:
        type: kafka
        topic: my_kafka_topic
        sasl:
          username: admin
          password: secret
        tls:
          skip-verify: true
        # other fields
        # ...
    ```
 - With server certificate verification
    ```yaml
    outputs:
      output1:
        type: kafka
        topic: my_kafka_topic
        sasl:
          username: admin
          password: secret
        tls:
          ca-file: /path/to/ca-file
        # other fields
        # ...
    ```
- With client certificates
    ```yaml
    outputs:
      output1:
        type: kafka
        topic: my_kafka_topic
        sasl:
          username: admin
          password: secret
        tls:
          cert-file: /path/to/cert-file
          key-file: /path/to/cert-file
        # other fields
        # ...
    ```
- With both server certificate verification and client certificates
    ```yaml
    outputs:
      output1:
        type: kafka
        topic: my_kafka_topic
        sasl:
          username: admin
          password: secret
        tls:
          cert-file: /path/to/cert-file
          key-file: /path/to/cert-file
          ca-file: /path/to/ca-file
        # other fields
        # ...
    ```
