### ISSUE TITLE
Multiple Ip router address for the same target

### ISSUE THREAD

**Issue by karimra** [karimra/gnmic#429]
### Discussed in https://github.com/karimra/gnmic/discussions/428

<div type='discussions-op-text'>

<sup>Originally posted by **dshah2012** July 24, 2021</sup>
Hello @karimra ,

Can i add multiple IP address under the same target. Since we have primary router IP and secondary router IP for a router. If one does not work then it should use the second.
I saw this documentation on the website. 
https://gnmic.kmrd.dev/user_guide/targets/
Like may be something like this for address  ?

```
targets:
  router1:
    name: router1
    address: primary-Ip-address:57400|secondary-Ip-address:57400
    username: username
    password: password
    subscriptions:
      - subscription_1
    outputs:
      - ouptut_1

```
So that it can automatically switch over to the other RP if there is a switch over. May be a functionality where it's dialing the first one and if its not able to connect it dials the second one.
Let me know will these work, or is there any other way this can be achieved using the existing functionalities ?
</div>
