### ISSUE TITLE
JQ event processor destroys unmatched events

### ISSUE THREAD

**Issue by jhujhiti** [karimra/gnmic#564]
I'm running version 0.24.1 and having an issue where the JQ event processor seems to be destroying events that don't match the configured condition. I'm able to reproduce with a very simple test case:

```yaml
skip-verify: true
log: true
debug: true
targets:
  lab1:
    address: x.x.x.x
    timeout: 2s
    skip-verify: true
outputs:
  prometheus:
    type: prometheus
    listen: :9804
    expiration: 600s
    metric-prefix: "gnmic"
    append-subscription-name: false
    override-timestamps: false
    export-timestamps: false
    strings-as-labels: true
    gnmi-cache: false
    timeout: 10s
    event-processors:
      - debug
      - lag-speed
      - debug
subscriptions:
  interfaces:
    encoding: JSON_IETF
    mode: STREAM
    paths:
      - /interface/lag/lag-speed
    sample-interval: 60s
    stream-mode: SAMPLE
processors:
  debug:
    event-write:
      tags:
        - ".*"
      dst: stdout
      indent: "  "
  # convert lag-speed megabits to bits
  lag-speed:
    event-jq:
      debug: true
      condition: "false"
      expression: '.[] | .values["/srl_nokia-interfaces:interface/srl_nokia-interfaces-lag:lag/lag-speed"] = .values["/srl_nokia-interfaces:interface/srl_nokia-interfaces-lag:lag/lag-speed"] * 1000000'
```

Setting `condition` to `"false"` causes what seems to be a sensible debug message: `2022/03/28 14:46:43.043792 /home/runner/work/gnmic/gnmic/formatters/event_jq/event_jq.go:120: [event-jq] condition jq result: (bool)false for input map[name:interfaces tags:map[interface_name:lag1 source:lab1 subscription-name:interfaces] timestamp:1648521574699644836 values:map[/srl_nokia-interfaces:interface/srl_nokia-interfaces-lag:lag/lag-speed:10000]]`, but the second `event-write` in the processor pipeline never emits anything, and the Prometheus endpoint returns no data. Setting `condition` to `"true"` does work as I would expect, although events from unrelated paths still seem to be destroyed. For instance, if I add `/interface/ethernet/port-speed` to the list of paths in the subscription, the first `event-write` proves that responses with that path were received, but nothing with that path is ever seen after the `event-jq` in the processor list regardless of the `condition` setting.
