### ISSUE TITLE
Kafka intermittent write issue 

### ISSUE THREAD

**Issue by dshah2012** [karimra/gnmic#586]
Hello @karimra,

I am running the GNMIC in a cluster mode and I see some intermittent errors in the Kafka output. Due to which some of the data is lost/dropped and is not sent to the kafka output and some of them pass through.

`writing expired after 5s, Kafka output might not be initialized` . 

This is my output config in the gnmic config. 
 
```
kafka_1:
    type: kafka
    name: ""
    address: broker_address1,broker_address2,broker_address3
    topic: kafka_topic
    format: protojson
    debug: true
    add-target: if-not-present
    sasl:
      mechanism: SCRAM-SHA-512
    tls:
      ca-file: /data/cacert.pem
      skip-verify: true
```

Is there anything that is wrong in the config or as the kafka output object is not initialized ?

Regards,
Darshan

**Comment by karimra** [comment]
Hi, that config looks OK (except the tls part, but it shouldn't be the cause of the timeout)
Did the amount of telemetry data collected by gnmic increase? More routers, more subscriptions?
You have 2 options to handle more traffic on the kafka output 

You can increase the timeout under kafka output (for e.g `timeout:10s`)

Or increase the number of kafka clients, `num-workers: 2`

Increasing the timeout will result on more goroutines running at the same time.

Increasing the number of workers will result on more kafka producers writing to the kafka broker.

**Comment by dshah2012** [comment]
Okay. The gnmic subscriptions are same but the target file has many targets. We had separated a target in multiple targets like this one. Since we have multiple subscription we had kept everything in one and we were facing the same issue that i am facing now and also  there was a single connection to the router if we had just one target with multiple subscription. 

So we thought of breaking down the targets and equally divide the subscription into the two of them. We thought that would solve the issue. 

For example below is the target file with single target breaking down to multiple with different subscription. 

```
Device1.optical:
  name: Device1.optical
  address: ip_address
  insecure: true
  subscriptions:
    - optics
  outputs:
    - kafka_output

Device1.isismulticast:
  name: Device1.isismulticast
  address: ip_address
  insecure: true
  subscriptions:
    - isis
    - multicast
  outputs:
    - kafka_output
```


I have tried both the approaches that you are suggesting but still getting the same issue. so if i give timeout and num-workers in the same config is there anything issue. Because i tried that too still the same issue
