### ISSUE TITLE
kafka input

### ISSUE THREAD

**Issue by karimra** [karimra/gnmic#604]
### Discussed in https://github.com/karimra/gnmic/discussions/603

<div type='discussions-op-text'>

<sup>Originally posted by **jrametta** June  2, 2022</sup>
Hi There!  Is it possible to have kafka input only in gnmic config such as below?  If so, what are the appropriate command line args to execute?

```
inputs:
  kafka-input:
    address: clab-fgw1-kafka-server:9002
    type: kafka
    topics: telemetry
    outputs:
      - prom-output

outputs:
  prom-output:
    type: prometheus
    listen: "gnmic:9804"
    service-registration:
      address: consul-agent:8500
```

tried with subscribe (but of course there are no subscriptions)

```
docker run --rm  -v foo.yaml:/etc/gnmic.conf  ghcr.io/karimra/gnmic:latest    sub --skip-verify
Error: no subscriptions configuration found
```

thanks!

</div>
