### ISSUE TITLE
OS freezing issues

### ISSUE THREAD

**Issue by LoboDCOK** [karimra/gnmic#608]
Hi this is my gnmi config

``` yaml
username: <edited>
password: <edited>
timeout: 10s
skip-verify: true
#no-prefix: true
log-file: /var/log/gnmic/gnmic.log
debug: false
qos: 20

targets:
  172.26.243.183:32767:
    name: <edited>
    encoding: PROTO
    subscriptions:
      - port_stats
      - rpm
    outputs:
      - output-influxdb
#      - output-file
  172.26.243.55:32767:
    name: <edited>
    encoding: PROTO
    subscriptions:
      - port_stats
      - rpm
    outputs:
      - output-influxdb
#      - output-file
  172.26.244.151:32767:
    name: <edited>
    encoding: PROTO
    subscriptions:
      - port_stats
      - rpm
    outputs:
      - output-influxdb
#      - output-file

subscriptions:
  port_stats:
    paths:
      - "/interfaces/interface/state/counters/"
      - "/interfaces/interface/subinterfaces/subinterface/state/counters/"
    mode: STREAM
#    stream-mode: SAMPLE
    stream-mode: TARGET_DEFINED
    sample-interval: 30s
    encoding: PROTO
    suppress-redundant: false
    updates-only: true
  rpm:
    paths:
      - "/junos/rpm/history-results"
    mode: STREAM
#    stream-mode: SAMPLE
    stream-mode: TARGET_DEFINED
    sample-interval: 30s
    encoding: PROTO
    suppress-redundant: false
    updates-only: true

outputs:
  output-file:
    type: file
    format: event
    filename: /var/log/gnmic/gnmic-out.json
    override-timestamp: false
    multiline: true
    indent: " "
    enabled-metrics: true
    event-processors:
      - add-tag-1
      - add-tag-2
      - delete-all
#      - delete-rpm
  output-influxdb:
    type: influxdb
    url: http://<edited>:8086
    org: AMX
    bucket: AMXGRAPH2
    token: <edited>
    batch-size: 1000
    flush-timer: 10s
    use-gzip: false
    enable-tls: false
#    override-timestamps: false
    override-timestamps: true
    health-check-period: 30s
    debug: false
    enable-metrics: false
    event-processors:
      - add-tag-1
      - add-tag-2
      - delete-all
#      - delete-rpm

processors:
  add-tag-1:
    event-add-tag:
      value-names:
        - "^/interfaces/interface/subinterfaces/subinterface/state/"
      add:
        subscription_type: "subinterfaces"
  add-tag-2:
    event-add-tag:
      value-names:
        - "^/interfaces/interface/state/"
      add:
        subscription_type: "interfaces"
#  delete-rpm:
#   event-delete:
#     tag-names:
#       - "history-single-test-results_owner"
  delete-all:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - trim-prefix:
            apply-on: "name"
            prefix: "/interfaces/interface/subinterfaces/subinterface/state/counters/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/interfaces/interface/state/counters/"
        - trim-prefix:
            apply-on: "name"
            prefix: "/junos/rpm/history-results/history-test-results/history-single-test-results/"
```

I tried to use this one in Debian & Ubuntu (both of them in their last version)

In both case, the OS is income freezing.

Do you have any idea why it's happened?
